In [3]:
import numpy as np 

str1 = np.array([['Python','NumPy','Exercises','Python'],
                 ['Python','Pandas','Exercises','Python'],
                 ['Python','Machine learning','Python','Python']])
print("Original array of string values:") 
print(str1)
print("\nCount 'Python' row wise in the above array of string values:")
print(np.char.count(str1, 'Python'))

Original array of string values:
[['Python' 'NumPy' 'Exercises' 'Python']
 ['Python' 'Pandas' 'Exercises' 'Python']
 ['Python' 'Machine learning' 'Python' 'Python']]

Count 'Python' row wise in the above array of string values:
[[1 0 0 1]
 [1 0 0 1]
 [1 0 1 1]]
