In [1]:
import pandas as pd
import numpy as np

In [5]:
serr = pd.Series([1,2,3,4,5])
serr

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
type(serr)

pandas.core.series.Series

In [9]:
serr.size

5

In [11]:
len(serr)

5

In [14]:
serr.ndim

1

In [15]:
serr.values

array([1, 2, 3, 4, 5], dtype=int64)

In [17]:
[i for i in serr.values]

[1, 2, 3, 4, 5]

In [18]:
serr2 = pd.Series([11,21,13,41,15,61,11,21,13,41,15,61,11,21,13,41,15,61])
serr2

0     11
1     21
2     13
3     41
4     15
5     61
6     11
7     21
8     13
9     41
10    15
11    61
12    11
13    21
14    13
15    41
16    15
17    61
dtype: int64

In [19]:
serr2.head()

0    11
1    21
2    13
3    41
4    15
dtype: int64

In [25]:
serr2.head(3)

0    11
1    21
2    13
dtype: int64

In [26]:
serr2.tail(3)

15    41
16    15
17    61
dtype: int64

In [28]:
list('clarusway')

['c', 'l', 'a', 'r', 'u', 's', 'w', 'a', 'y']

In [29]:
pd.Series(['c', 'l', 'a', 'r', 'u', 's', 'w', 'a', 'y'])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

In [34]:
data = ["paris", "london", "ankara"]
index = ["x","y","z"]

In [35]:
pd.Series(data,index)

x     paris
y    london
z    ankara
dtype: object

In [36]:
Score = [70,60,90,85, 99.5]
index = ["D","E","A","B","C"]
pd.Series(Score,index)


D    70.0
E    60.0
A    90.0
B    85.0
C    99.5
dtype: float64

In [37]:
dic = {"D":10,"E":20,"A":-30,"B":99,"C":1.1}
pd.Series(dic)

D    10.0
E    20.0
A   -30.0
B    99.0
C     1.1
dtype: float64

In [40]:
a = set ([3,2,45,4,3,4,32,4,5,5,4])
a

{2, 3, 4, 5, 32, 45}

In [43]:
pd.Series(list(a))

0    32
1     2
2     3
3     4
4     5
5    45
dtype: int64

In [44]:
ser1 = pd.Series([1,2,3,4], index = ['USA', 'Germany','USSR', 'Japan'])
ser2 = pd.Series([1,2,5,4], index = ['USA', 'Germany','Italy', 'Japan'])

In [47]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [48]:
ser1.index

Index(['USA', 'Germany', 'USSR', 'Japan'], dtype='object')

In [49]:
ser1.values

array([1, 2, 3, 4], dtype=int64)

In [51]:
ser1.sort_index()

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [52]:
ser1.sort_values()

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [53]:
ser2.sort_index()

Germany    2
Italy      5
Japan      4
USA        1
dtype: int64

In [54]:
ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
dtype: int64

In [55]:
ser1["Germany"]

2

In [56]:
ser1["Japan"]

4

In [58]:
ser1[["Japan", "Germany"]]

Japan      4
Germany    2
dtype: int64

In [59]:
ser1.Japan

4

In [60]:
ser1+ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [65]:
panser = pd.Series(data   = [121, 200, 150, 99, 145, 120, 180],
                    index = ["terry", "micheal", "orion", "jason","adam", "thomas", "zack"])
panser

terry      121
micheal    200
orion      150
jason       99
adam       145
thomas     120
zack       180
dtype: int64

In [66]:
panser.jason

99

In [67]:
panser["jason"]

99

In [69]:
panser["orion":"adam"]

orion    150
jason     99
adam     145
dtype: int64

In [70]:
panser[["orion","adam"]]

orion    150
adam     145
dtype: int64

In [72]:
panser[2:5]

orion    150
jason     99
adam     145
dtype: int64

In [74]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason', 'adam', 'thomas', 'zack'], dtype='object')

In [75]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason', 'adam', 'thomas', 'zack'], dtype='object')

In [81]:
panser.values

array([121, 200, 150,  99, 145, 120, 180], dtype=int64)

In [85]:
list(panser.items())

[('terry', 121),
 ('micheal', 200),
 ('orion', 150),
 ('jason', 99),
 ('adam', 145),
 ('thomas', 120),
 ('zack', 180)]

In [86]:
for key, value in panser.items():
    print("key: ",key,"\t value:", value)

key:  terry 	 value: 121
key:  micheal 	 value: 200
key:  orion 	 value: 150
key:  jason 	 value: 99
key:  adam 	 value: 145
key:  thomas 	 value: 120
key:  zack 	 value: 180


In [87]:
"adam" in panser

True

In [89]:
121 in panser.values

True

In [96]:
panser.isin([121,99])

terry       True
micheal    False
orion      False
jason       True
adam       False
thomas     False
zack       False
dtype: bool

In [97]:
panser.jason = 190
panser

terry      121
micheal    200
orion      150
jason      190
adam       145
thomas     120
zack       180
dtype: int64

In [98]:
panser>=180

terry      False
micheal     True
orion      False
jason       True
adam       False
thomas     False
zack        True
dtype: bool

In [99]:
panser[panser>=180] = 155
panser

terry      121
micheal    155
orion      150
jason      155
adam       145
thomas     120
zack       155
dtype: int64