## Lab-1

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5,6,7,8]

In [3]:
a=np.array(my_list)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
b=a[:3]
b

array([1, 2, 3])

In [5]:
b[0]=88
b

array([88,  2,  3])

In [6]:
a

array([88,  2,  3,  4,  5,  6,  7,  8])

In [7]:
c=a.copy()
c[1]=22
c

array([88, 22,  3,  4,  5,  6,  7,  8])

In [8]:
a

array([88,  2,  3,  4,  5,  6,  7,  8])

In [9]:
type(c)

numpy.ndarray

In [10]:
a.shape

(8,)

In [11]:
a[-1]

8

In [12]:
a[::-1]

array([ 8,  7,  6,  5,  4,  3,  2, 88])

In [13]:
b = np.array([[1,2,3], [6,7,8]])

In [14]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [15]:
b[1,1]=77
b

array([[ 1,  2,  3],
       [ 6, 77,  8]])

In [19]:
b[:,1]=99

In [20]:
b

array([[ 1, 99,  3],
       [ 6, 99,  8]])

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.full((3,3), 9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [24]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.arange(5, 60, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59])

In [27]:
np.linspace(5, 60, 3)

array([ 5. , 32.5, 60. ])

In [28]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [29]:
np.random.rand(3,3)

array([[0.90446262, 0.27847953, 0.80434534],
       [0.24327832, 0.10382959, 0.35589283],
       [0.39008088, 0.36871535, 0.96650478]])

In [30]:
np.random.randn(3,3)

array([[-1.3077338 ,  0.16303099,  0.51082194],
       [ 0.47573474,  0.64552693,  0.98583704],
       [ 0.99945142, -0.33390186,  0.6893033 ]])

In [32]:
np.random.randint(5,10,size=(3,3))

array([[5, 8, 7],
       [8, 8, 5],
       [9, 7, 7]])

In [33]:
z = np.random.randint(2,15, size = (5,3))
z

array([[ 4,  8,  9],
       [ 6,  7, 11],
       [ 5,  3,  6],
       [11,  6,  8],
       [ 5, 11, 14]])

In [34]:
z.shape

(5, 3)

In [37]:
z.size

15

In [36]:
z=z.reshape(3,5)
z

array([[ 4,  8,  9,  6,  7],
       [11,  5,  3,  6, 11],
       [ 6,  8,  5, 11, 14]])

In [38]:
z=z.reshape(-1,5)
z

array([[ 4,  8,  9,  6,  7],
       [11,  5,  3,  6, 11],
       [ 6,  8,  5, 11, 14]])

In [39]:
z=z.ravel()
z

array([ 4,  8,  9,  6,  7, 11,  5,  3,  6, 11,  6,  8,  5, 11, 14])

In [40]:
z.max()

14

In [41]:
z.min()

3

In [42]:
z.argmax()

14

In [43]:
z.argmin()

7

**Concatenate**

In [44]:
my_arr = np.array([0,1,2,3,4,5,6,7,8,9]).reshape(5,2)

In [45]:
my_arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [47]:
my_arr_1 = np.array([3,4,5,6,7,8,9,10,11,12]).reshape(5,2)
my_arr_1

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [50]:
my_con=np.concatenate([my_arr,my_arr_1],axis=1)
my_con

array([[ 0,  1,  3,  4],
       [ 2,  3,  5,  6],
       [ 4,  5,  7,  8],
       [ 6,  7,  9, 10],
       [ 8,  9, 11, 12]])

** Indexing & Selection **

In [51]:
my_con

array([[ 0,  1,  3,  4],
       [ 2,  3,  5,  6],
       [ 4,  5,  7,  8],
       [ 6,  7,  9, 10],
       [ 8,  9, 11, 12]])

In [52]:
my_con[1,[2,3]]

array([5, 6])

In [53]:
my_con[[3,1],2]

array([9, 5])

In [54]:
my_con[0:2,1:3]

array([[1, 3],
       [3, 5]])

In [55]:
my_con[:,[0,3]]

array([[ 0,  4],
       [ 2,  6],
       [ 4,  8],
       [ 6, 10],
       [ 8, 12]])

## Stacking

In [56]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [57]:
a

array([[1, 2],
       [3, 4]])

In [58]:
b

array([[5, 6],
       [7, 8]])

In [59]:
x=np.stack((a,b))
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [60]:
x.ndim

3

In [61]:
x.shape

(2, 2, 2)

In [62]:
y=np.hstack((a,b))
y

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [63]:
y=np.vstack((a,b))
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [64]:
array_1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])
array_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
bigger_than_5=array_1>5
bigger_than_5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [67]:
array_1[bigger_than_5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [68]:
array_1[array_1<5]

array([1, 2, 3, 4])

In [69]:
array_1[(array_1<10) & (array_1>3)]

array([4, 5, 6, 7, 8, 9])

In [70]:
array_1[(array_1<10) | (array_1>3)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

In [72]:
x

array([[1, 2],
       [3, 4]])

In [73]:
y

array([[5, 6],
       [7, 8]])

In [74]:
x+y

array([[ 6,  8],
       [10, 12]])

In [75]:
x-y

array([[-4, -4],
       [-4, -4]])

In [76]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [77]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [78]:
x*y

array([[ 5, 12],
       [21, 32]])

In [79]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [80]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [82]:
x

array([[1, 2],
       [3, 4]])

In [81]:
x**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [84]:
np.power(x,2)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [83]:
np.sqrt(np.power(x,2))

array([[1., 2.],
       [3., 4.]])

In [85]:
np.log(x)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [86]:
np.exp(x)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [87]:
import pandas as pd

In [88]:
my_list = [1,2,3,4,5,6,7,8]
a=np.array(my_list)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
pd.Series(my_list)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [90]:
labels = ['X','y','z', 'h']
my_list = [5, 10, 15, 20]
arr = np.array([25, 50, 75, 100])
d = {'a': 10, 'b': 20, 'c': 30, 'd':40}

In [91]:
pd.Series(my_list,index=labels)

X     5
y    10
z    15
h    20
dtype: int64

In [92]:
pd.Series(arr)

0     25
1     50
2     75
3    100
dtype: int32

In [93]:
pd.Series(d)

a    10
b    20
c    30
d    40
dtype: int64

In [94]:
mix_data = [7, "dog", False, np.arange]

In [95]:
pd.Series(mix_data)

0                             7
1                           dog
2                         False
3    <built-in function arange>
dtype: object

In [97]:
ser = pd.Series([5,10,15,100,25,30], index = ['USA', 'Germany','France', 'UK','Turkey','Greece'])
ser

USA          5
Germany     10
France      15
UK         100
Turkey      25
Greece      30
dtype: int64

In [98]:
ser.sort_values()

USA          5
Germany     10
France      15
Turkey      25
Greece      30
UK         100
dtype: int64

In [99]:
ser.sort_index()

France      15
Germany     10
Greece      30
Turkey      25
UK         100
USA          5
dtype: int64

In [101]:
'Holland' in ser

False

In [103]:
ser.isin([25])

USA        False
Germany    False
France     False
UK         False
Turkey      True
Greece     False
dtype: bool

In [104]:
ser.keys()

Index(['USA', 'Germany', 'France', 'UK', 'Turkey', 'Greece'], dtype='object')

In [106]:
ser.items

<bound method Series.items of USA          5
Germany     10
France      15
UK         100
Turkey      25
Greece      30
dtype: int64>

In [107]:
for key,value in ser.items():
    print(key,value)
    

USA 5
Germany 10
France 15
UK 100
Turkey 25
Greece 30


In [108]:
m = np.arange(1,30,2).reshape((3,5))
m

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [109]:
df=pd.DataFrame(m, columns=['col1','col2','col3','col4','col5'])

In [110]:
df

col1  col2  col3  col4  col5
0     1     3     5     7     9
1    11    13    15    17    19
2    21    23    25    27    29

In [112]:
df.head(1)

col1  col2  col3  col4  col5
0     1     3     5     7     9

In [113]:
df.tail(2)

col1  col2  col3  col4  col5
1    11    13    15    17    19
2    21    23    25    27    29

In [117]:
df.sample(2)

col1  col2  col3  col4  col5
1    11    13    15    17    19
2    21    23    25    27    29