In [1]:
import numpy as np
import pandas as pd

In [2]:
my_list = [1,2,3,4,5,6,7,8]

In [3]:
a = np.array(my_list)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
b = a[:3]
b

array([1, 2, 3])

In [5]:
b[0] = 88
b

array([88,  2,  3])

In [6]:
a

array([88,  2,  3,  4,  5,  6,  7,  8])

In [7]:
c = a.copy()
c

array([88,  2,  3,  4,  5,  6,  7,  8])

In [8]:
c[1] = 22
c

array([88, 22,  3,  4,  5,  6,  7,  8])

In [9]:
a

array([88,  2,  3,  4,  5,  6,  7,  8])

In [10]:
type(c)

numpy.ndarray

In [11]:
a.shape

(8,)

In [12]:
a[-1]

8

In [13]:
a[::-1]

array([ 8,  7,  6,  5,  4,  3,  2, 88])

In [22]:
b = np.array([[1,2,3], [6,7,8]])

In [23]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [16]:
b[1,1] = 77
b

array([[ 1,  2,  3],
       [ 6, 77,  8]])

In [18]:
b[:,1] = 99
b

array([[ 1, 99,  3],
       [ 6, 99,  8]])

In [25]:
b[[0,1],[1,2]]

array([2, 8])

In [26]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [38]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.11856462e-320],
       [1.11261027e-306, 8.01026589e-307, 4.54923304e-307]])

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.arange(5,60,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59])

In [31]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [39]:
np.random.rand(3,3)

array([[0.22277039, 0.26759049, 0.86066733],
       [0.6713246 , 0.57948378, 0.55645925],
       [0.29002689, 0.60557485, 0.39284619]])

In [40]:
np.random.randn(3,3)

array([[ 1.17561879, -0.18691768, -2.04377138],
       [ 1.34290388, -0.99626005,  0.54695298],
       [-1.17677614, -0.26943408,  0.98060583]])

In [42]:
np.random.randint(5,10,size=(3,3))

array([[7, 5, 5],
       [5, 9, 7],
       [7, 6, 7]])

In [44]:
z = np.random.randint(2,15, size = (5,3))
z

array([[ 4,  8, 14],
       [ 2, 10,  7],
       [ 5,  2, 12],
       [ 5,  9,  9],
       [ 2,  7,  3]])

In [45]:
z.shape

(5, 3)

In [46]:
z = z.reshape(3,5)
z

array([[ 4,  8, 14,  2, 10],
       [ 7,  5,  2, 12,  5],
       [ 9,  9,  2,  7,  3]])

In [49]:
z = z.reshape(-1,5)
z

array([[ 4,  8, 14,  2, 10],
       [ 7,  5,  2, 12,  5],
       [ 9,  9,  2,  7,  3]])

In [50]:
z = z.ravel()
z

array([ 4,  8, 14,  2, 10,  7,  5,  2, 12,  5,  9,  9,  2,  7,  3])

In [51]:
z.max()

14

In [52]:
z.min()

2

In [53]:
z.argmax()

2

In [54]:
my_arr = np.array([0,1,2,3,4,5,6,7,8,9]).reshape(5,2)
my_arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [55]:
my_arr1 = np.array([1,1,22,35,46,65,66,76,86,96]).reshape(5,2)
my_arr1

array([[ 1,  1],
       [22, 35],
       [46, 65],
       [66, 76],
       [86, 96]])

In [56]:
my_con = np.concatenate([my_arr,my_arr1],axis=1)
my_con 

array([[ 0,  1,  1,  1],
       [ 2,  3, 22, 35],
       [ 4,  5, 46, 65],
       [ 6,  7, 66, 76],
       [ 8,  9, 86, 96]])

In [57]:
my_con[1,[2,3]]

array([22, 35])

In [58]:
my_con[[3,1],2]

array([66, 22])

In [59]:
my_con[0:2,1:3]

array([[ 1,  1],
       [ 3, 22]])

In [61]:
my_con[:,[0,3]]

array([[ 0,  1],
       [ 2, 35],
       [ 4, 65],
       [ 6, 76],
       [ 8, 96]])

In [62]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [63]:
a

array([[1, 2],
       [3, 4]])

In [64]:
b

array([[5, 6],
       [7, 8]])

In [65]:
x = np.stack((a,b))
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [66]:
x.ndim

3

In [67]:
x.shape

(2, 2, 2)

In [68]:
y =np.hstack((a,b))
y

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [69]:
y =np.vstack((a,b))
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [70]:
array_1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])
array_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
bigger_than_5 = array_1>5
bigger_than_5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [72]:
array_1[bigger_than_5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [75]:
array_1[(array_1<10) & (array_1>3)]

array([4, 5, 6, 7, 8, 9])

In [76]:
array_1[(array_1<10) | (array_1>3)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [77]:
my_list = [1,2,3,4,5,6,7,8]
a=np.array(my_list)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
pd.Series(my_list)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [79]:
labels = ['X','y','z', 'h']
my_list = [5, 10, 15, 20]
arr = np.array([25, 50, 75, 100])
d = {'a': 10, 'b': 20, 'c': 30, 'd':40}

In [80]:
pd.Series(my_list, index = labels)

X     5
y    10
z    15
h    20
dtype: int64

In [82]:
pd.Series(d)

a    10
b    20
c    30
d    40
dtype: int64

In [85]:
ser = pd.Series([5,10,150,25,20,30], index = ['USA', 'Germany','France', 'UK','Turkey','Greece'])
ser

USA          5
Germany     10
France     150
UK          25
Turkey      20
Greece      30
dtype: int64

In [86]:
ser.sort_values()

USA          5
Germany     10
Turkey      20
UK          25
Greece      30
France     150
dtype: int64

In [87]:
ser.sort_index()

France     150
Germany     10
Greece      30
Turkey      20
UK          25
USA          5
dtype: int64

In [88]:
ser.isin(["55"])

USA        False
Germany    False
France     False
UK         False
Turkey     False
Greece     False
dtype: bool

In [89]:
ser.isin(["25"])

USA        False
Germany    False
France     False
UK         False
Turkey     False
Greece     False
dtype: bool

In [90]:
ser.keys()

Index(['USA', 'Germany', 'France', 'UK', 'Turkey', 'Greece'], dtype='object')

In [91]:
ser.items

<bound method Series.items of USA          5
Germany     10
France     150
UK          25
Turkey      20
Greece      30
dtype: int64>

In [92]:
m = np.arange(1,30,2).reshape((3,5))
m

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [93]:
df = pd.DataFrame(m)

In [94]:
df

0   1   2   3   4
0   1   3   5   7   9
1  11  13  15  17  19
2  21  23  25  27  29

In [95]:
df.head()

0   1   2   3   4
0   1   3   5   7   9
1  11  13  15  17  19
2  21  23  25  27  29

In [96]:
df.sample(2)

0   1   2   3   4
0   1   3   5   7   9
1  11  13  15  17  19