___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.array([1, 3, 5])

array([1, 3, 5])

In [3]:
pd.Series ( [1, 3, 5])

0    1
1    3
2    5
dtype: int64

In [4]:
ser = pd.Series([1,3,5])

In [5]:
ser


0    1
1    3
2    5
dtype: int64

In [6]:
ser.dtype

dtype('int64')

In [7]:
ser.size

3

In [8]:
ser.ndim

1

In [9]:
ser

0    1
1    3
2    5
dtype: int64

In [10]:
ser.values

array([1, 3, 5], dtype=int64)

In [11]:
type(ser.values)

numpy.ndarray

In [12]:
ser.index

RangeIndex(start=0, stop=3, step=1)

In [13]:
ser.values

array([1, 3, 5], dtype=int64)

In [14]:
for _ in ser.values:
    print(_)

1
3
5


In [16]:
[i for i in ser.values]

[1, 3, 5]

In [17]:
list(ser.values)

[1, 3, 5]

In [18]:
ser.to_list()

[1, 3, 5]

In [27]:
ser = pd.Series ( [i for i in range(10)])

In [28]:
ser


0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [31]:
ser.head(5)

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [34]:
ser.tail(9)

1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [36]:
ser.sample(n=5)

9    9
5    5
0    0
7    7
8    8
dtype: int64

In [39]:
ser.sample(frac=.3).size

3

In [40]:
[i for i in 'clarusway']

['c', 'l', 'a', 'r', 'u', 's', 'w', 'a', 'y']

In [41]:
pd.Series([i for i in 'clarusway'])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

In [49]:
labels =  ['a', 'b', 'c', 'd']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30, 40])
d = {'a': 10, 'b': 20, 'c': 30}

In [50]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [51]:
pd.Series(data=arr)

0    10
1    20
2    30
3    40
dtype: int32

In [52]:
pd.Series(data=arr, index = labels)

a    10
b    20
c    30
d    40
dtype: int32

In [53]:
d


{'a': 10, 'b': 20, 'c': 30}

In [54]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [60]:
d


{'a': 10, 'b': 20, 'c': 30}

In [61]:
pd.Series(data=d, index=["q", 'c', 'w'])

q     NaN
c    30.0
w     NaN
dtype: float64

In [62]:
myset = {1, 2, 4}
pd.Series(data=myset)

TypeError: 'set' type is unordered

In [64]:
pd.Series( tuple(myset))


0    1
1    2
2    4
dtype: int64

In [65]:
pd.Series( [myset, 'x', print     ]       )


0                    {1, 2, 4}
1                            x
2    <built-in function print>
dtype: object

In [69]:
a = pd.Series( [myset, 'x', print     ]  , index=['x', 'y','z']     )

In [70]:
a[0]

{1, 2, 4}

In [71]:
a

x                    {1, 2, 4}
y                            x
z    <built-in function print>
dtype: object

In [72]:
a.index = [ 'set', 'str', 'print'  ]

In [73]:
a

set                      {1, 2, 4}
str                              x
print    <built-in function print>
dtype: object

In [75]:
ser1 = pd.Series( [1,2,3,4], index=['USA', 'Germany', 'USSR', 'Japan'])
ser2 = pd.Series( [1,2,5,4], index=['USA', 'Germany', 'Italy','Japan'])


In [76]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [77]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [80]:
ser1.sort_index(ascending=True)

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [81]:
ser1.sort_index(ascending=False)

USSR       3
USA        1
Japan      4
Germany    2
dtype: int64

In [82]:
ser1.sort_values(ascending=True)

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [83]:
ser1.sort_values(ascending=False)

Japan      4
USSR       3
Germany    2
USA        1
dtype: int64

In [84]:
ser1


USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [86]:
a = ser1.sort_index(ascending=True)
a

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [87]:
ser1.sort_index(ascending=True, inplace=True)

In [88]:
ser1

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [89]:
x = ser1.copy()

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [90]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [91]:
ser2['Germany':'Italy']

Germany    2
Italy      5
dtype: int64

In [92]:
ser2[1:2]

Germany    2
dtype: int64

In [107]:
ser2[1]

2

In [93]:
ser1

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [94]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [100]:
added = ser1 + ser2
added

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [96]:
ser1.isnull()

Germany    False
Japan      False
USA        False
USSR       False
dtype: bool

In [98]:
added.isnull()

Germany    False
Italy       True
Japan      False
USA        False
USSR        True
dtype: bool

In [102]:
ser1.isnull().any()

False

In [103]:
added.isnull().any()

True

In [104]:
added.isnull().all()

False

In [106]:
pd.NaT  #sort like NaN

NaT

In [108]:
a = np.array( [1, 2, 33, 444, 75])
panser = pd.Series(a)
panser

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [109]:
panser[3]

444

In [110]:
panser[0:1]

0    1
dtype: int32

In [111]:
panser.index 

RangeIndex(start=0, stop=5, step=1)

In [113]:
panser.index = ['terry', 'michael', 'orion', 'jason', 'quinn']

In [114]:
panser

terry        1
michael      2
orion       33
jason      444
quinn       75
dtype: int32

In [115]:
panser['quinn']  #.loc

75

In [116]:
panser[4]         #.iloc

75

In [117]:
ix = ['terry' , 'michael', 'jason']
ix


['terry', 'michael', 'jason']

In [118]:
d

{'a': 10, 'b': 20, 'c': 30}

In [119]:
pd.Series(d, index=['a'])

a    10
dtype: int64

In [120]:
panser[ix]

terry        1
michael      2
jason      444
dtype: int32

In [121]:
panser

terry        1
michael      2
orion       33
jason      444
quinn       75
dtype: int32

In [122]:
panser['terry':'quinn']

terry        1
michael      2
orion       33
jason      444
quinn       75
dtype: int32

In [123]:
panser.keys

<bound method Series.keys of terry        1
michael      2
orion       33
jason      444
quinn       75
dtype: int32>

In [124]:
panser.keys()

Index(['terry', 'michael', 'orion', 'jason', 'quinn'], dtype='object')

In [126]:
panser.index

Index(['terry', 'michael', 'orion', 'jason', 'quinn'], dtype='object')

In [127]:
panser.values

array([  1,   2,  33, 444,  75])

In [128]:
panser.items

<bound method Series.items of terry        1
michael      2
orion       33
jason      444
quinn       75
dtype: int32>

In [129]:
panser.items()

In [130]:
list(panser.items())

[('terry', 1), ('michael', 2), ('orion', 33), ('jason', 444), ('quinn', 75)]

In [131]:
for index_value, num_value in panser.items():
    print(index_value, num_value)

terry 1
michael 2
orion 33
jason 444
quinn 75


In [132]:
d

{'a': 10, 'b': 20, 'c': 30}

In [133]:
'a' in d

True

In [134]:
'quinn' in panser

True

In [135]:
'Trump' in panser

False

In [136]:
panser

terry        1
michael      2
orion       33
jason      444
quinn       75
dtype: int32

In [138]:
panser.isin([444])

terry      False
michael    False
orion      False
jason       True
quinn      False
dtype: bool

In [139]:
type(panser.isin([444]))

pandas.core.series.Series

In [140]:
panser.isin([444]).all()

False

In [141]:
panser.isin([444]).any()

True

In [142]:
panser.isin([444, 75, 33])

terry      False
michael    False
orion       True
jason       True
quinn       True
dtype: bool

In [143]:
panser


terry        1
michael      2
orion       33
jason      444
quinn       75
dtype: int32

In [144]:
panser['terry'] = 666

In [145]:
panser

terry      666
michael      2
orion       33
jason      444
quinn       75
dtype: int32

In [150]:
panser['michael'] = 1.01345

In [151]:
panser

terry          666
michael    1.01345
orion           33
jason          444
quinn           75
dtype: object

In [148]:
panser['michael'] = 'aaaa'

In [149]:
panser

terry       666
michael    aaaa
orion        33
jason       444
quinn        75
dtype: object

In [152]:
panser['michael'] = 234

In [153]:
panser


terry      666
michael    234
orion       33
jason      444
quinn       75
dtype: object

In [154]:
panser.astype(int)

terry      666
michael    234
orion       33
jason      444
quinn       75
dtype: int32

In [155]:
panser[ panser > 100     ]

terry      666
michael    234
jason      444
dtype: object

In [156]:
panser > 100

terry       True
michael     True
orion      False
jason       True
quinn      False
dtype: bool

In [158]:
myeval = panser > 100  # &   |
panser [myeval]

terry      666
michael    234
jason      444
dtype: object

In [159]:
panser * myeval

terry      666
michael    234
orion        0
jason      444
quinn        0
dtype: object

In [160]:
data = [1, 2, 39, 67, 90]

In [161]:
panser [ ['terry', 'quinn'] ]

terry    666
quinn     75
dtype: object

In [162]:
data

[1, 2, 39, 67, 90]

In [163]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [164]:
pd.DataFrame(data)

0
0   1
1   2
2  39
3  67
4  90

In [165]:
pd.DataFrame(data, columns=['first_col'])

first_col
0          1
1          2
2         39
3         67
4         90

In [166]:
data2 = np.arange(1,10).reshape(3,3)

In [167]:
data2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [168]:
pd.DataFrame(data2, columns=['var1', 'var2', 'var3'])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [169]:
data3 = np.arange(1, 101).reshape(25, 4)

In [171]:
df3 = pd.DataFrame(data3,columns=['var1', 'var2', 'var3', 'var4'])

In [174]:
df3.head(3)

var1  var2  var3  var4
0     1     2     3     4
1     5     6     7     8
2     9    10    11    12

In [175]:
df3.tail(2)

var1  var2  var3  var4
23    93    94    95    96
24    97    98    99   100

In [177]:
df3.sample(n=2)

var1  var2  var3  var4
8    33    34    35    36
7    29    30    31    32

In [178]:
df3.columns

Index(['var1', 'var2', 'var3', 'var4'], dtype='object')

In [179]:
type(df3.columns)

pandas.core.indexes.base.Index

In [181]:
for _ in df3.columns:
    print(_)

var1
var2
var3
var4


In [191]:
df3.columns = ['newcol1', 'newcol2', 'newcol3', 'newcol4']

In [192]:
df3

newcol1  newcol2  newcol3  newcol4
0         1        2        3        4
1         5        6        7        8
2         9       10       11       12
3        13       14       15       16
4        17       18       19       20
5        21       22       23       24
6        25       26       27       28
7        29       30       31       32
8        33       34       35       36
9        37       38       39       40
10       41       42       43       44
11       45       46       47       48
12       49       50       51       52
13       53       54       55       56
14       57       58       59       60
15       61       62       63       64
16       65       66       67       68
17       69       70       71       72
18       73       74       75       76
19       77       78       79       80
20       81       82       83       84
21       85       86       87       88
22       89       90       91       92
23       93       94       95       96
24       97       98       99      100

In [193]:
df3.shape  #(25, 4, 3)

(25, 4)

In [194]:
df3.ndim

2

In [195]:
df3.size

100

In [200]:
#PanDaS   Panel = 3d  
pd.read_clipboard()

Empty DataFrame
Columns: [22, 89, 90]
Index: []

In [202]:
with open ('data.csv', 'w') as fh:
    fh.write('1, 2, 3')

    

In [203]:
df = pd.read_csv('data.csv')

In [204]:
df

Empty DataFrame
Columns: [1,  2,  3]
Index: []