___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

In [2]:
import numpy as np
arr = np.arange(0,11)  #np.array()   np.ones   np.zeros ....
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[8]

8

In [5]:
arr[-1]

10

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[1::2]   #arr[first_elem, last_elem, stride]

array([1, 3, 5, 7, 9])

In [8]:
arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

In [9]:
arr[3] = 333
arr

array([  0,   1,   2, 333,   4,   5,   6,   7,   8,   9,  10])

In [14]:
arr[:3] = 666
arr

array([666, 666, 666, 333,   4,   5,   6,   7,   8,   9,  10])

In [17]:
lst = [1, 2, 3]
for _ in range(len(lst)-1):
    lst[_ ]  = 777
lst

[777, 777, 3]

In [18]:
arr[::] = 888
arr

array([888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888])

In [19]:
lst = [1, 2, 3]
lst_copy = lst
lst[0] = 666
lst

[666, 2, 3]

In [20]:
lst_copy

[666, 2, 3]

In [21]:
id(lst)==id(lst_copy)

True

In [22]:
arr


array([888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888])

In [23]:
arr[0] = 0
arr


array([  0, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888])

In [24]:
arr_copy = arr
arr_copy[0] = -999


In [25]:
arr

array([-999,  888,  888,  888,  888,  888,  888,  888,  888,  888,  888])

In [27]:
array_copy = arr[:2]
array_copy

array([-999,  888])

In [28]:
array_copy[1] = -777
array_copy

array([-999, -777])

In [29]:
arr

array([-999, -777,  888,  888,  888,  888,  888,  888,  888,  888,  888])

In [30]:
array_copy.base

array([-999, -777,  888,  888,  888,  888,  888,  888,  888,  888,  888])

In [32]:
#id(array_copy.base)==id(arr)

True

In [33]:
true_copy = arr.copy()

In [34]:
true_copy

array([-999, -777,  888,  888,  888,  888,  888,  888,  888,  888,  888])

In [35]:
id(true_copy) == id(arr)

False

In [36]:
another_true_copy = arr[:]
another_true_copy

array([-999, -777,  888,  888,  888,  888,  888,  888,  888,  888,  888])

In [37]:
id(another_true_copy) == id(arr)

False

In [38]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
arr_2d[0]

array([ 5, 10, 15])

In [41]:
r = arr_2d[1]

In [42]:
type(r)

numpy.ndarray

In [43]:
r[0]

20

In [44]:
type(r[0])

numpy.int32

In [45]:
arr_2d[1][0]

20

In [46]:
arr_2d[1,0]

20

In [47]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [48]:
arr_2d[ 0:2     ,  1: ]

array([[10, 15],
       [25, 30]])

In [49]:
arr_2d[: , 1 ]

array([10, 25, 40])

In [50]:
arr_2d [ :   , :2  ]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [51]:
arr_tiny = np.array([10, 20, 30], dtype=np.int8)
arr_tiny

array([10, 20, 30], dtype=int8)

In [54]:
arr_tiny[1] = 666
arr_tiny

array([  10, -102,   30], dtype=int8)

In [56]:
arr_2d.dtype

dtype('int32')

In [57]:
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [58]:
arr_2d[0, 0 ] = 666
arr_2d

array([[666,  10,  15],
       [ 20,  25,  30],
       [ 35,  40,  45]])

In [59]:
arr_2d[0, 0 ] = 666.666
arr_2d

array([[666,  10,  15],
       [ 20,  25,  30],
       [ 35,  40,  45]])

In [60]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [61]:
v[1]

3

In [62]:
v[-1]

27

In [63]:
v[1:3]

array([3, 6])

In [66]:
# array [    [list_of_elements]      ]
index_list = [7, 3, 6]
v[ index_list ]

array([21,  9, 18])

In [67]:
v [ [7, 3, 6]   ]

array([21,  9, 18])

In [68]:
arr2d = np.zeros( (10, 10), dtype=int    )
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [69]:
arr2d.dtype

dtype('int32')

In [70]:
arr2d.shape

(10, 10)

In [71]:
rows, columns = arr2d.shape


In [72]:
rows

10

In [73]:
arr2d[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [76]:
for i in range(rows):
    arr2d[i] = i

In [77]:
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [79]:
arr2d[  [3, 7, 4, 3]  ]

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [80]:
jj = np.arange(1, 17).reshape(4, 4)

In [81]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [82]:
jj [ [0, 2, 3]       ,   [0, 1, 3]          ]
#zip ( [0, 2, 3], [0, 1, 3] )
#jj [0, 0], jj [2, 1], jj [3, 3]

array([ 1, 10, 16])

In [83]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [84]:
jj[ 1  , [1, 2]   ]

array([6, 7])

In [85]:
jj [ [1, 2], 1    ]

array([ 6, 10])

In [86]:
jj[ :  ,  [1, 2] ]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [90]:
jj[ 1:3,  [1, 2] ]

array([[ 6,  7],
       [10, 11]])

In [91]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
arr > 4 # >  ==  >=   <=

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [93]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [94]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [96]:
arr [  [1, 2]           ]
arr [ bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [106]:
arr [ (arr!=3) & (arr!=4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

In [107]:
# arr [ (arr<2) | (arr>8)]  # ^ xor   (bit-wise operators)

array([ 1,  9, 10])

In [108]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
arr + arr # __add__() method of ndarray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [110]:
arr * 2   # __mul__()

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [111]:
arr - arr #__sub__()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [115]:
import warnings
warnings.filterwarnings('ignore')

arr /  arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [116]:
np.nan  # None   is_null()   #np.nat (or close to that)

nan

In [118]:
np.NaN

nan

In [119]:
np.NAN

nan

In [123]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [124]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [126]:
arr % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [127]:
arr * 3  / 10 - 9

array([-9. , -8.7, -8.4, -8.1, -7.8, -7.5, -7.2, -6.9, -6.6, -6.3])

In [128]:
arr.dtype

dtype('int32')

In [129]:
a = arr * 3  / 10 - 9
a.dtype

dtype('float64')

In [130]:
# + - / % * **   (arr.__add__    np.add())
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [133]:
np.exp(arr)   #element-wise   e^<element>

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [134]:
np.max(arr)   #numpy universal functions

9

In [135]:
np.sin

<ufunc 'sin'>

In [137]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [138]:
np.sin(np.pi/2)

1.0

In [139]:
np.tan(np.pi/4)

0.9999999999999999

In [140]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [141]:
np.log10(10)

1.0

In [142]:
np.log10(100)

2.0

In [144]:
np.mean(v)


13.5

In [145]:
np.median(v)

13.5

In [146]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [148]:
d=np.array(((0,1,2,3), (10,11,12,13),(20,21,22,23)))
d

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [149]:
d.max()

23

In [151]:
d.max(axis=1)

array([ 3, 13, 23])

In [153]:
np.std(d, axis=0)

array([8.16496581, 8.16496581, 8.16496581, 8.16496581])

In [154]:
np.std(d)

8.241156876717412

In [155]:
from scipy import stats
stats.describe(d)

DescribeResult(nobs=3, minmax=(array([0, 1, 2, 3]), array([20, 21, 22, 23])), mean=array([10., 11., 12., 13.]), variance=array([100., 100., 100., 100.]), skewness=array([0., 0., 0., 0.]), kurtosis=array([-1.5, -1.5, -1.5, -1.5]))

In [156]:
d

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [160]:
np.corrcoef(d)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [161]:
d

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [162]:
d % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [163]:
d * ( d%2)

array([[ 0,  1,  0,  3],
       [ 0, 11,  0, 13],
       [ 0, 21,  0, 23]])

In [164]:
np.ma

<module 'numpy.ma' from 'C:\\Anaconda3\\lib\\site-packages\\numpy\\ma\\__init__.py'>

In [165]:
np.ma.masked_array

numpy.ma.core.MaskedArray

In [172]:
g = np.array( [ 1, np.nan, 3])
m = np.ma.masked_array(g, [True, True, False] )

In [173]:
m

masked_array(data=[--, --, 3.0],
             mask=[ True,  True, False],
       fill_value=1e+20)

In [174]:
m.mean()

3.0

In [175]:
d

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [176]:
d.ravel()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23])

In [177]:
d.flat

In [179]:
it = d.flat
next (it)

0

In [192]:
d

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [193]:
e = d.ravel()

In [194]:
e

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23])

In [195]:
len(e)

12

In [196]:
r = 4
c = len(e) // r
d.reshape( r, c   )

array([[ 0,  1,  2],
       [ 3, 10, 11],
       [12, 13, 20],
       [21, 22, 23]])

In [200]:
rs = np.resize(d, (2,2)  )

In [204]:
rs

array([[0, 1],
       [2, 3]])

In [201]:
np.resize(d, (2,3)  )

array([[ 0,  1,  2],
       [ 3, 10, 11]])

In [203]:
np.resize(rs, (5, 5))

array([[0, 1, 2, 3, 0],
       [1, 2, 3, 0, 1],
       [2, 3, 0, 1, 2],
       [3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0]])

In [205]:
rs_copy = rs


In [211]:
np.resize(rs_copy, (2,3))

C:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[0, 1, 2],
       [3, 0, 1]])

In [210]:
warnings.resetwarnings()


In [212]:
rs

array([[0, 1],
       [2, 3]])

In [213]:
x = np.resize(rs, (1,2))

In [214]:
x


array([[0, 1]])

In [215]:
np.resize(x, (3, 3))

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]])

In [216]:
np.fromiter

<function numpy.fromiter>

In [218]:
np.fromiter([i for i in range(1000)], dtype=int)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [219]:
np.fromiter(range(1000), dtype=int)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [221]:
np.fromiter((3, 2, 5), dtype=int)

array([3, 2, 5])

In [222]:
rs.flat


In [223]:
np.fromiter(rs.flat, dtype=int)

array([0, 1, 2, 3])